### ISSUE TITLE
[Doc] ドキュメントを作る

### ISSUE THREAD

**Issue by yamamoto-yuta** [richcat-dev/richcat#100]
[Sphinx](https://www.sphinx-doc.org/ja/master/)とか使ってドキュメント作っておきたいですね．そろそろプログラムの全体像思い出すのがしんどくなってきたので．

**Comment by ShotaroKataoka** [comment]
sphinxでhtmlビルドしようとしたら怒られた
![image](https://user-images.githubusercontent.com/42331656/104992935-5e95bb80-5a65-11eb-9e5c-de641df37932.png)

miport関係複雑になってるからなー

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
なぜかcssが読み込まれてないけど作るだけできた
https://richcat-dev.github.io/richcat/

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
いいですね！これでクラスとかモジュールとかのメンテナンスが楽になりますね

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
cssないよね？

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
はい．CSS適用されてなくてHTMLべた書きになってますね

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
なんでですかねー
ローカルでプレビューしたときはcssとかあったんだけど

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
ローカルとオンラインでソースファイル比較したら，オンラインの方はCSSファイルが空になってましたね（custom.css以外は埋まってるはず）．buildとかmakeってしました？

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
`sphinx-autobuild -b html ./doc/sphinx docs`
こんなコマンドでビルドしてた

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
一旦，新しいリポジトリ作ってSphinxの使い方ある程度把握してからrichcatに適用する，って感じにした方が良さそうですね…

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
sphinxのせいかは微妙だが

**Comment by ShotaroKataoka** [comment]
css自体はあるが，なぜかホスティングされてない

**Comment by yamamoto-yuta** [comment]
ローカルで動作確認できたのでcloseします
