### ISSUE TITLE
[Doc] GitHub Pages上でCSSが適用されない

### ISSUE THREAD

**Issue by yamamoto-yuta** [richcat-dev/richcat#104]
@ShotaroKataoka 
はい．CSS適用されてなくてHTMLべた書きになってますね

_Originally posted by @yamamoto-yuta in https://github.com/richcat-dev/richcat/issues/100#issuecomment-762640932_

**Comment by yamamoto-yuta** [comment]
`sphinx.ext.githubpages`を試してみたんですがダメでした…ディレクトリ構造の問題…？

> SphinxとGitHub Pagesで技術ノートを公開しよう！
> https://qiita.com/tutuz/items/88a32d94d700b33dc3ea#github-pages-%E3%81%A8%E3%81%AE%E9%80%A3%E6%90%BA

**Comment by ShotaroKataoka** [comment]
その可能性ある
settingsで`docs/`をgithub pagesにしてるけど`/`にしたら直るのかも？

**Comment by yamamoto-yuta** [comment]
今確認したら行けてました． @ShotaroKataoka さんの環境ではどうですか？
![image](https://user-images.githubusercontent.com/55144709/105677015-aff2ee80-5f2e-11eb-863b-89d147779302.png)

**Comment by ShotaroKataoka** [comment]
いけてるわ
なぜ

**Comment by yamamoto-yuta** [comment]
これを適用しました．反映に予想以上（10分以上？）時間がかかるのかもですね…

> そうすると、CSS が見事きいていないことがわかります。悲しいですね。
> GitHi Pages は、デフォルトで JekyII でホスティングを行います。しかし、JekyII は Sphinx に対応していないため、 _static などにあるパスを読み取ることができません。対応として .nojekyll のディレクトリを作成する必要があります。手動で作成しても問題ないですが、今回は sphinx.ext.githubpages を用いて対応することができます。
> sphinx.ext.githubpages プラグインは GitHub Pages で公開するために、 .nojekyll ファイルをHTMLディレクトリ内に作成します。
> https://qiita.com/tutuz/items/88a32d94d700b33dc3ea#github-pages-%E3%81%A8%E3%81%AE%E9%80%A3%E6%90%BA

**Comment by yamamoto-yuta** [comment]
問題なく動いてるので一旦closeします

**Comment by yamamoto-yuta** [comment]
#110 で再発したのでreopen
