### ISSUE TITLE
v0.5.0リリースノート作成

### ISSUE THREAD

**Issue by yamamoto-yuta** [richcat-dev/richcat#111]
ついでにリリースノート作成時にPyPIへの登録とかもGitHub Actionsでできると、バージョンや内容の差異が踏まれなくて良いかも

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
#121 にてワークフローでリリース作成することになったので、リリースノートに書く内容をこのissueで議論しようかなと思ってるんですが、どうですか？（こういうのってissueで議論すべきなんですかね？）

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
確かにバージョン決めて開発しますね…

リリースノート作成をissueやる目的は、「このバージョンのリリースノートこれで良いんだっけ？これ抜けてない？この表現分かりにくくない？」みたいなのをやるためですね

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 

> v0.x.xリリースノート作成

ひとまず↑でやってみます！

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
リリースノート、こんな感じでどうですか？

---

## ✨ New Feature
- Support `.ipynb` format files

## 🐛 Bug Fix
- Bug fixed to cause an error if the `-w` option was not specified when pipe input.

## Others
- `richcat` documentation is available: https://richcat-dev.github.io/richcat/

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
良いと思います！

**Comment by yamamoto-yuta** [comment]
反映したのでcloseします
https://github.com/richcat-dev/richcat/releases/tag/v0.5.0
