### ISSUE TITLE
PyPIへの登録をGithub Actionsで行うようにする

### ISSUE THREAD

**Issue by yamamoto-yuta** [richcat-dev/richcat#116]

**Comment by yamamoto-yuta** [comment]
参考記事：
- [PyPIパッケージ公開手順 - Qiita](https://qiita.com/shinichi-takii/items/e90dcf7550ef13b047b5)
- [pypi-publish · Actions · GitHub Marketplace](https://github.com/marketplace/actions/pypi-publish)
- [Github Actions 使ったらPypiへのリリースがめちゃくちゃ楽になった - Qiita](https://qiita.com/th4inf/items/d9e575095d35f8f6720e)
- [Publishing package distribution releases using GitHub Actions CI/CD workflows — Python Packaging User Guide](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/)
- [Help · PyPI](https://pypi.org/help/#apitoken)

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
開発からPyPIアップロードまでのフローを考えてみたので、コメントいただいても良いでしょうか:bow:

フロー：

1. developブランチ開発
1. releaseブランチで余計なファイルを削除
1. main←release のPR作成時にTestPyPIへアップロード（Dockerで立てたTestPyPI実行環境にて動作確認が可能）
1. mainブランチへpush
1. `git tag` でバージョンをタグ付け
1. Releaseを作成
1. Release作成完了時にワークフローでバージョン不整合の確認とPyPIへのアップロードを行う

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
良いと思います
TestPyPIにアップロードするときもバージョン確認コード走らせてもいいと思う

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
バージョン確認は以下の2つが等しいことを確認するって感じですかね？

- __information__.py で定義されているバージョン
- ブランチ名中のバージョン文字列
