### ISSUE TITLE
拡張子辞書更新したら `md` が `markdown` に変換されるようになった

### ISSUE THREAD

**Issue by yamamoto-yuta** [richcat-dev/richcat#132]
以下のcommitにて、 `.md` ファイルの `filetype` が `md` ではなく `markdown` に変換されるようになった。

- https://github.com/richcat-dev/richcat/commit/7587cfa397713b7486e0a36d8c1d7612b3694103#diff-6977d1bb60a917798e6cb575c6a984969e4998a4dbcb7ad78986f1403e04beb5R359-R360

その結果、Markdownファイルであるにも関わらず以下の行のif文はtrueにならず、MarkdownファイルがMarkdownファイルとして処理されなくなってしまった。

- https://github.com/richcat-dev/richcat/blob/develop/richcat/richcat.py#L139

![image](https://user-images.githubusercontent.com/55144709/155151945-35aebb2c-1007-4061-a1cb-904eaa9d3179.png)

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
自動更新ワークフローを更新を発見したときにプルリクを出す仕組みにするのはどう？

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
それ良いですね！その方向でちょっと進めてみます（ワークフローでPRを自動作成するアイデアも他のワークフローで応用できそう）

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
そもそもこの辞書ってそんなに必要なのか？rich本体についている拡張子推論機能を使えば良くない？みたいな気持ちになってるので、一旦検証したほうが良いかもですね…

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
拡張子推論機能使ってないのは遅いからとかじゃなかったっけ？

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
自分もそう記憶してるんですが、ワークフロー組んだり色々してる労力とそれによって得られている速度感が釣り合ってるのか？って感じです

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
体感できるくらい違ったような気がするから，パフォーマンス的には一番差がつく気がする

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
計測はしておきたいですね。何秒くらい改善したのか？とか分かってた方が良いので。ちょっと別リポジトリに計測環境作ってみます。

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
以下のリポジトリで簡単に計測してみました。辞書使った方が爆速みたいです。

- [richcat-dev/richcat-guess-lexer-dev: richcatのファイル形式推論処理の処理時間を計測するためのリポジトリ](https://github.com/richcat-dev/richcat-guess-lexer-dev)

![image](https://user-images.githubusercontent.com/55144709/155389515-275b97ba-7455-4bef-9ff4-1ef66a8457bf.png)
![image](https://user-images.githubusercontent.com/55144709/155389592-49ac8d62-4006-49d9-ad57-e9dff0dcb938.png)

**Comment by ShotaroKataoka** [comment]
1桁違うんか

**Comment by yamamoto-yuta** [comment]
https://github.com/richcat-dev/richcat/issues/132#issuecomment-1048450724

**Comment by yamamoto-yuta** [comment]
> https://github.com/richcat-dev/richcat/issues/132#issuecomment-1048450724

developへpushされたら辞書更新される＝developへのPRで更新された辞書がレビュー対象になるので、わざわざ新たにPR作らなくても良い気がしました。どうですか？

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
ひとまずこのissueの件はmergeして処理します。辞書更新を新しいPRでやるべきかは #134 で議論しましょう！
