### ISSUE TITLE
v0.5.0 rc 動作報告

### ISSUE THREAD

**Issue by ShotaroKataoka** [richcat-dev/richcat#138]
@yamamoto-yuta 
事前に `pip install rich==11.1.0` を行うとインストールできた
`pip install rich` だと `11.2.0` とかで失敗した

`debug/Untitled.ipynb` を表示したら，json形式で出力された

**Comment by ShotaroKataoka** [comment]
インストールされてるのは`0.5.0rc0`
![image](https://user-images.githubusercontent.com/42331656/155828161-1f2f4566-99af-4a5d-8c9e-b36b0c354381.png)

**Comment by ShotaroKataoka** [comment]
jupyterがインストールされてる仮想環境じゃなかったので，インストールしなおしたけどjsonが出力された
python上で
```python
from richcat import richcat
richcat('debug/Untitled.ipynb')
```
したらmdになった

**Comment by yamamoto-yuta** [comment]
## 問題
TestPyPIからインストールすると、以下のようなエラーが発生する。

環境：ローカルの `richcat-play` コンテナ内

```
root@1242602ca523:~# pip install -i https://test.pypi.org/simple/ richcat==0.5.0rc0
WARNING: The directory '/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Looking in indexes: https://test.pypi.org/simple/
Collecting richcat==0.5.0rc0
  Downloading https://test-files.pythonhosted.org/packages/16/b0/8e1f8962532983e087a84e83e81694e1d43e70f81d1658ef62fdbd016727/richcat-0.5.0rc0-py3-none-any.whl (19 kB)
ERROR: Could not find a version that satisfies the requirement sphinx-autobuild==2021.3.14 (from richcat) (from versions: none)
ERROR: No matching distribution found for sphinx-autobuild==2021.3.14
```

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 

https://github.com/richcat-dev/richcat/issues/138#issuecomment-1051564284

↑これどこの環境で実行しました？

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
ふつうにローカル

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
これはtestpypiサーバにsphinx-autobuild==2021.3.14
がないからですね
Pypiから先に該当のやつインストールせんといかん

> ## 問題
> TestPyPIからインストールすると、以下のようなエラーが発生する。
> 
> 環境：ローカルの `richcat-play` コンテナ内
> 
> ```
> root@1242602ca523:~# pip install -i https://test.pypi.org/simple/ richcat==0.5.0rc0
> WARNING: The directory '/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
> Looking in indexes: https://test.pypi.org/simple/
> Collecting richcat==0.5.0rc0
>   Downloading https://test-files.pythonhosted.org/packages/16/b0/8e1f8962532983e087a84e83e81694e1d43e70f81d1658ef62fdbd016727/richcat-0.5.0rc0-py3-none-any.whl (19 kB)
> ERROR: Could not find a version that satisfies the requirement sphinx-autobuild==2021.3.14 (from richcat) (from versions: none)
> ERROR: No matching distribution found for sphinx-autobuild==2021.3.14
> ```
>

**Comment by yamamoto-yuta** [comment]
> @yamamoto-yuta これはtestpypiサーバにsphinx-autobuild==2021.3.14 がないからですね Pypiから先に該当のやつインストールせんといかん
> 
> > ## 問題
> > TestPyPIからインストールすると、以下のようなエラーが発生する。
> > 環境：ローカルの `richcat-play` コンテナ内
> > ```
> > root@1242602ca523:~# pip install -i https://test.pypi.org/simple/ richcat==0.5.0rc0
> > WARNING: The directory '/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
> > Looking in indexes: https://test.pypi.org/simple/
> > Collecting richcat==0.5.0rc0
> >   Downloading https://test-files.pythonhosted.org/packages/16/b0/8e1f8962532983e087a84e83e81694e1d43e70f81d1658ef62fdbd016727/richcat-0.5.0rc0-py3-none-any.whl (19 kB)
> > ERROR: Could not find a version that satisfies the requirement sphinx-autobuild==2021.3.14 (from richcat) (from versions: none)
> > ERROR: No matching distribution found for sphinx-autobuild==2021.3.14
> > ```

以下のコマンドで解決しました。

```
$ python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ richcat==0.5.0rc0
```

公式ドキュメントに書いてありましたね…

> If you want to allow pip to also download packages from PyPI, you can specify --extra-index-url to point to PyPI. This is useful when the package you’re testing has dependencies:
> 引用：[Using TestPyPI — Python Packaging User Guide](https://packaging.python.org/en/latest/guides/using-testpypi/#using-testpypi-with-pip)

**Comment by ShotaroKataoka** [comment]
> > @yamamoto-yuta ふつうにローカル
> 
> @ShotaroKataoka 
> それは素のWSL+Ubuntuの環境にそのまま入れたという解釈で合ってますか？

そんな感じ

**Comment by yamamoto-yuta** [comment]
> jupyterがインストールされてる仮想環境じゃなかったので，インストールしなおしたけどjsonが出力された python上で
> 
> ```python
> from richcat import richcat
> richcat('debug/Untitled.ipynb')
> ```
> 
> したらmdになった



> > > @yamamoto-yuta ふつうにローカル
> > 
> > 
> > @ShotaroKataoka
> > それは素のWSL+Ubuntuの環境にそのまま入れたという解釈で合ってますか？
> 
> そんな感じ

自分の環境だとこの条件でも正常に動きました。

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
`richcat-play` コンテナ環境に以下の変更を加えたので、releaseブランチとdevelopブランチを最新の状態に更新をお願いします:bow:
- aliasにTestPyPIからrichcatをインストールするためのコマンドを追加しました。 `install-richcat 0.5.0rc0` みたいな感じでインストールできるようになってます。
- コンテナ内に `debug/` 内のファイルをマウントしました。これでコンテナ内で `debug/` 内のファイルでrichcatの動作確認が可能です。


コミット：https://github.com/richcat-dev/richcat/commits/release/v0.5.0

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
素の環境でうまく動いてないの、スクショとか撮れたりしますか？

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
ローカルの本環境にjupyterなし，venvにrichcatとjupyterという環境だと
python内のみで表示できる

**Comment by ShotaroKataoka** [comment]
スクショとっても分からんと思う

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
表示できた
本環境とかvenv環境とかのrichcatがぶつかってたらしい

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
![image](https://user-images.githubusercontent.com/42331656/155870617-79121eb4-80a7-49be-a371-d07002c18ce9.png)
その代わり，なんか幅が変やわ

**Comment by ShotaroKataoka** [comment]
Untitled.ipynb は変になる
jupyter_notebook.ipynb は大丈夫

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
自分の環境だとvenv環境でも正常に動きました。というか出力セルの内容が表示されてるのおかしいですね…clear-outputするよう指定しているはずなので。
![image](https://user-images.githubusercontent.com/55144709/155870938-fed174a2-711b-46f0-bcab-3e241ad657a3.png)

**Comment by ShotaroKataoka** [comment]
わからん

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
コードは最新のものになってますか？

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
なってる
jupyterはversion1.0.0

**Comment by ShotaroKataoka** [comment]
> > @yamamoto-yuta 表示できた 本環境とかvenv環境とかのrichcatがぶつかってたらしい
> 
> @ShotaroKataoka あ、自分もvenv内でvenv外でインストールしたrichcat使っちゃってました…


@yamamoto-yuta 
- 本環境：richcatのみ
- venv：richcat+jupyter
の場合，venv内でrichcatをするとjupyterが利用できない
venvでpythonに入って`from richcat import richcat`をするとvenvのrichcatを使うのでjupyterを表示できるみたい

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
つまり、「素の環境とvenv環境で競合した場合、素の環境の方が優先される」のが原因って感じですかね

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
venv環境を作った後reloginすると、ちゃんとvenv内のrichcatが呼ばれるようになりました。

venv環境を作る→richcatをインストールする→ `which richcat` した場合のrichcatのパス：
```
/home/yamamoto/.local/bin/richcat
```

上記の後、reloginする→venv環境に入る→ `which richcat` した場合のrichcatのパス：
```
/home/yamamoto/develop/richcat/richcat-play-env/env/bin/richcat
```

試したときのログ全体：
```
❯ which richcat
/home/yamamoto/.local/bin/richcat
❯ which jupyter
jupyter not found
❯ venv
❯ activate
❯ pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ richcat==0.5.0rc0
～～～（出力省略）～～～
❯ which richcat
/home/yamamoto/.local/bin/richcat
❯ deactivate
❯ which richcat
/home/yamamoto/.local/bin/richcat
❯ relogin
❯ which richcat
/home/yamamoto/.local/bin/richcat
❯ activate
❯ which richcat
/home/yamamoto/develop/richcat/richcat-play-env/env/bin/richcat
```

**Comment by ShotaroKataoka** [comment]
whichはvenvになってるけど、なんかだめなんすよね

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
自分の環境だと想定通り動いてます…

venv環境：
![image](https://user-images.githubusercontent.com/55144709/155887506-fa873e79-d0b9-43e6-a98d-5eef3c2054be.png)

素の環境：
![image](https://user-images.githubusercontent.com/55144709/155887522-db8bd069-c011-4461-8d54-22d0e995b343.png)

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
インストールしなおしたりしたらvenvと素の環境で使い分けはできるようになった
ただ，幅がずれるのは直ってない
![image](https://user-images.githubusercontent.com/42331656/156080366-649841eb-7bdd-4b0d-9fa8-215448cd7339.png)

**Comment by ShotaroKataoka** [comment]
https://stackoverflow.com/questions/28908319/how-to-clear-jupyter-notebooks-output-in-all-cells-from-the-linux-terminal

jupyterのバージョンによって`--clear-output`が効かないらしい

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
こうするとできました
```python
            out, err = subprocess.Popen(f'jupyter nbconvert --ClearOutputPreprocessor.enabled=True --to notebook --stdout --log-level WARN {filepath}'.split(' '), stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
```


↓みたいな雰囲気でバージョンチェックするといいと思います
バージョンチェックの部分は適当（1.0.0a0とかだとエラーになる）なので修正してもらうのと
どのバージョンが境目になるかは分からないのでよろしくお願いします
```python
        jupyter = import_module_with_existence_confirmation('jupyter')
        if jupyter is not None:
            version = int(''.join([f'{int(v):0=3}' for v in jupyter.__version__.split('.')]))
            if version<=int(''.join([f'{int(v):0=3}' for v in '1.0.0'.split('.')])):
                out, err = subprocess.Popen(f'jupyter nbconvert --ClearOutputPreprocessor.enabled=True --to notebook --stdout --log-level WARN {filepath}'.split(' '), stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
            else:
                out, err = subprocess.Popen(f'jupyter nbconvert --clear-output --stdout --log-level WARN {filepath}'.split(' '), stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
```
![image](https://user-images.githubusercontent.com/42331656/156081864-a17fe6ae-dc01-4f1d-8639-a383d5951a83.png)

**Comment by ShotaroKataoka** [comment]
`jupyter nbconvert -V`でチェックした方が良いかも
ちなみに当環境では`5.6.1`だった

https://github.com/jupyter/nbconvert/issues/822
修正は6.0.0くらいかも

**Comment by ShotaroKataoka** [comment]
nbconvert別物だわ
`pip install nbconvert --upgrade`じゃないとバージョンアップされんし
チェックもこれでした方が良いし，わんちゃんpythonのライブラリで今の処理できるかも
![image](https://user-images.githubusercontent.com/42331656/156084259-dfe1cd41-56d1-44c6-a9f4-05841e9a3f1c.png)

**Comment by ShotaroKataoka** [comment]
さらに言うとバージョン関係なく下で動く
```python
            out, err = subprocess.Popen(f'jupyter nbconvert --ClearOutputPreprocessor.enabled=True --to notebook --stdout --log-level WARN {filepath}'.split(' '), stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
```

**Comment by ShotaroKataoka** [comment]
v0.5.0はいったん↑を修正してもらってでいいと思う

v0.5.xでnbconvertのライブラリ実行を変更してもいいかも
https://nbconvert.readthedocs.io/en/latest/nbconvert_library.html

**Comment by yamamoto-yuta** [comment]
> さらに言うとバージョン関係なく↓で動くのでバージョンチェックせずに一律これにすればいいか
> 
> ```python
>             out, err = subprocess.Popen(f'jupyter nbconvert --ClearOutputPreprocessor.enabled=True --to notebook --stdout --log-level WARN {filepath}'.split(' '), stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
> ```

@ShotaroKataoka 

これ反映した0.5.0rc2をTestPyPIにリリースしました！これで動作確認をお願いします:bow:
https://test.pypi.org/project/richcat/#history

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
では、release→mainでPR出します！

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
0.5.0おめでとうございます:tada:
