### ISSUE TITLE
[table] カラム名どうするか

### ISSUE THREAD

**Issue by ShotaroKataoka** [richcat-dev/richcat#18]

**Comment by yamamoto-yuta** [comment]
`--use-header`等，オプションでしていされたら1行目をヘッダとして利用する

**Comment by yamamoto-yuta** [comment]
`--disable-pager`とか`--user-header`とかにせず，batみたいに
```
--style="number,changes,header"
```
みたいな感じで指定するほうが良いかも…？

**Comment by yamamoto-yuta** [comment]
Python argparseヘルプ表示の複数行
https://www.366service.com/jp/qa/ae41a1f2adc078ac9bee1d7cecd19ceb
