### ISSUE TITLE
[-t option] Syntaxのとき-t optionが効かない

### ISSUE THREAD

**Issue by ShotaroKataoka** [richcat-dev/richcat#19]
Syntax実装をfrom_pathにしてるから-tしてもファイルタイプの指定が出来てない
-tが指定されているときはfile_pathじゃなくする分岐がいるかも（拡張子ない奴を`-t zsh`って指定するときとかにzsh sintaxされない）

そこまで致命的なバグではないから，優先度低めで

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
デバッグ用にサンプルファイルもらえませんか？

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
例えば `test.py` って名前で
```
echo "hello world"
a=bbb
echo $a
```
このファイル作ってみて，`richcat test.py -t zsh` で実行してみて

![image](https://user-images.githubusercontent.com/42331656/100194133-7e62a480-2f38-11eb-8fb7-d8c4779324f3.png)

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
イマイチこのオプションの使いどころが見えないんですが，具体的にどんな用途で使うことを想定してますか？T

**Comment by yamamoto-yuta** [comment]
![image](https://user-images.githubusercontent.com/55144709/100257230-0cff1200-2f89-11eb-94b2-cc79e2de96a0.png)

対応できました

**Comment by yamamoto-yuta** [comment]
解決したのでcloseにします
