### ISSUE TITLE
batみたいに別ウィンドウ？で開いてスクロールさせる感じにしたい

### ISSUE THREAD

**Issue by yamamoto-yuta** [richcat-dev/richcat#20]

**Comment by ShotaroKataoka** [comment]
batってそんな仕組みなの？

**Comment by ShotaroKataoka** [comment]
なるほど
これか
![image](https://user-images.githubusercontent.com/42331656/99907550-a677bb00-2d20-11eb-9ef0-511c0f76413b.png)

**Comment by ShotaroKataoka** [comment]
![image](https://user-images.githubusercontent.com/42331656/99907731-c5c31800-2d21-11eb-942c-e2d77f1f8176.png)
shellなら `richcat a.md | less`
みたいなかんじでless使うとできるみたい

**Comment by ShotaroKataoka** [comment]
subprocessでless使うといけるかも（未検証）

**Comment by ShotaroKataoka** [comment]
richの-pオプションでpagerがオンになる
ただしなぜか色が失われた
![image](https://user-images.githubusercontent.com/42331656/99921322-06944e80-2d6d-11eb-870d-19e0dc691292.png)

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
richの-pオプションでpagerがオンになる
ただしなぜか色が失われた
![image](https://user-images.githubusercontent.com/42331656/99921322-06944e80-2d6d-11eb-870d-19e0dc691292.png)

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
https://tangerina.jp/blog/python-with-pager/
こんなの見つかった
pagerで調べるといいかも

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
https://rich.readthedocs.io/en/latest/console.html#paging
元々サポートされてるっぽい

**Comment by ShotaroKataoka** [comment]
色に関しては
```
Since the default pager on most platforms don’t support color, Rich will strip color from the output. If you know that your pager supports color, you can set styles=True when calling the pager() method.
```
元々pagerは色をサポートしてないけどstyle=Trueで色つけれるらしい(？)

**Comment by yamamoto-yuta** [comment]
rich内臓pagerの `styles=True` で行けました．

気になる点としてはコチラ：
- Markdownのリンクが無効になっている（Ctrl + クリックで飛べない）
  - そもそも，リンクを Ctrl + クリックして飛べる機能自体がWindows Terminal Preview Ver.1.5 の新機能か

```
with console.pager(styles=True):
    console.print(<RICH_TEXT_GENERATOR>)
```

![image](https://user-images.githubusercontent.com/55144709/99990669-73ecc180-2df7-11eb-96f6-382e06a1cf48.png)

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
pagerのstyle=Trueの説明に色を付ける部分を切り離してるみないなこと書いてたような気がするからリンクは無理かもね
`-p`か`-l`かなんかのオプションでpagerのオンオフはできた方がいいと思う

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
batだと `--paging=never` でpagerをOFFにできるみたいなので，そんな感じで切り替えられるようにしてみます．

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
↓でpagerをOFFにできるようにしました．これで問題なければissueをcloseにしてブランチをmergeします．
```
richcat --disable_pager <FILE_PATH>
```

**Comment by yamamoto-yuta** [comment]
mergeしたのでcloseします
