### ISSUE TITLE
[Implementation] console.print()もiRichMakerインタフェースに含める

### ISSUE THREAD

**Issue by yamamoto-yuta** [richcat-dev/richcat#22]
以前のipynb実装時に `console.print()` をforで回したことがあるため，print処理もインタフェースに含める構造にした方が良いかも？
もう少し色々ファイルタイプ対応してから検討するのが良いか？

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
renderって関数あると分かりやすいかも

**Comment by ShotaroKataoka** [comment]
後で全然いいと思う

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
今はprintは別々で回してる？グループかなんかでひとつのオブジェクトにしてる？

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
printはファイルタイプごとに別々でやってますね

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
なるほどです
全部描写するRender関数かなんか作ってもいいかもね
Markdownの場合とかMarkdownとtableが混在するし、renderableオブジェクトがいくつあっても順番に全部render呼んで描写してくれるとか

**Comment by ShotaroKataoka** [comment]
Renderableは描写する順番にひとつのリストに格納しといて最後に一気にconsol.printするのがよさそう？

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
少し考えてみたんですが，ファイルタイプごとにprint時の処理が変わる可能性がありそうなので，↓みたいな実装にするのが良いかなと思いました．
・継承方法を，iRichMakerインタフェースからAbstractRichMakerという抽象クラスに変更
・AbstractRichMakerにデフォルトのrenderメソッドを用意，あるファイルタイプで標準出力処理が変わる場合はrenderメソッドをoverrideして実装

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta  
なるほど！いいと思います！

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
↓でpagerをOFFにできるようにしました．これで問題なければissueをcloseにしてブランチをmergeします．
```
richcat --disable_pager <FILE_PATH>
```

**Comment by yamamoto-yuta** [comment]
#20 を実装する際に，抽象クラスへの変更とprint処理をクラス内メソッドとして内包する変更を行ったのでcloseします．
