### ISSUE TITLE
[critical issue] PyPIにアップロードしたv0.1.0が動かない

### ISSUE THREAD

**Issue by ShotaroKataoka** [richcat-dev/richcat#27]
![image](https://user-images.githubusercontent.com/42331656/100321334-de734c80-3005-11eb-8296-251f32e45e8e.png)

https://qiita.com/shonansurvivors/items/0fbcbfde129f2d26301c#3-setuppy%E3%81%AE%E4%BD%9C%E6%88%90
![image](https://user-images.githubusercontent.com/42331656/100321387-f21eb300-3005-11eb-8081-3767ec3b7502.png)
packages=[~~~]でrichcatのほかにrichcat.modulesを指定しないといけないかも
ls-improvedでは１つのディレクトリで複数ファイルを扱ってたから知らなかったけど，ディレクトリが複数ある場合は全部指定しないといけないかもしれない

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
PyPIの0.1.0はYankしました
（Deleteは非推奨＆一度アップロードするとそのバージョン名は二度と使えなくなる）
Yankするとrichcat==0.1.0とかって指定しない限りインストーラーに無視されるようになります

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
自作モジュールの場合，ディレクトリ内に `__init__.py` を設置する必要があるみたいです．
https://qiita.com/ktgwaaa/items/6d1f54d5ff3c4559f96c#%E8%87%AA%E4%BD%9C%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%81%AE%E5%A0%B4%E5%90%88__init__py%E3%82%92%E5%BF%98%E3%82%8C%E3%81%AA%E3%81%84%E3%82%88%E3%81%86%E3%81%AB
