### ISSUE TITLE
[implementation] filetypeのデフォルト値'auto'をやめる

### ISSUE THREAD

**Issue by yamamoto-yuta** [richcat-dev/richcat#32]
Noneが良さげ．pygmentsか何かが'auto'をデフォルト値にしていたような気がするので調べる

**Comment by yamamoto-yuta** [comment]
`AbstractRichMaker`クラスに関しては，そもそもTable, Markdown, Syntaxのどれにするかの分岐にfiletypeを利用するため，インスタンス化する時点でfiletypeは必ず何かしらの値で埋まっている．したがってデフォルト値を定めておく必要が無い．

**Comment by yamamoto-yuta** [comment]
コマンドライン引数の方の'auto'については，前述の分岐のための拡張子抽出処理で使用しているため必要

**Comment by yamamoto-yuta** [comment]
合った方が実装上都合が良い（filetypeを気にするのがSyntaxのみで，MarkdownとTableには関係ないため）ことが分かったので残します．issueもcloseにします．

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
対応しないときはその理由とともにwontfix(修正しない)ラベルを付けると分かりやすくていいっすよ

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
なるほどです:bow:
