### ISSUE TITLE
[CUI]pipeで使えるようにする

### ISSUE THREAD

**Issue by yamamoto-yuta** [richcat-dev/richcat#38]
今やるとこんなエラーが出る
```
$ echo hello | richcat
usage: richcat [-h] [-t [FileType]] [-w [Width]] [-c [Width]] [--disable-pager] FilePath
richcat: error: the following arguments are required: FilePath
```

**Comment by yamamoto-yuta** [comment]
[Pythonでコマンドの実行結果の標準出力を取得する - 作業ノート](https://te2u.hatenablog.jp/entry/2015/07/15/235240)

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
これは
`echo "$PWD/$filename" | richcat`
みたいな動作を想定してる？

richechoがあっても悪くないなと思いました（要るかどうかは不明だけど）

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
そんな感じです。これできると、既存のhead, tailが使えるようになるので。

**Comment by ShotaroKataoka** [comment]
なるほど
head, tailはすでにできるくない？
pipe出力はできるよ（pipe入力ができないだけで）
![image](https://user-images.githubusercontent.com/42331656/101436505-a3e8a880-3951-11eb-9983-ea8943fb2b41.png)

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
pipe出力はもうできたんですね…優先度大分低くなりました

**Comment by yamamoto-yuta** [comment]
予想以上に実装が難しいことが分かったので，一旦見送ります．
[sedもawkも使えないけどpythonでパイプに参加テク - Qiita](https://qiita.com/apollo_program/items/44adb2b5aaea90fb2150)
[运行Utils.py时总是有这个问题 · Issue #1 · WuJie1010/Facial-Expression-Recognition.Pytorch](https://github.com/WuJie1010/Facial-Expression-Recognition.Pytorch/issues/1)

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
https://stackoverflow.com/questions/8478137/how-redirect-a-shell-command-output-to-a-python-script-input
これは？

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
これ僕の方でちょっと試してみます

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
パイプ結果は取得できたんですが，`stty size` でエラーが出るようになります．このエラーはPython由来のもののようです．

参考記事：
[运行Utils.py时总是有这个问题 · Issue #1 · WuJie1010/Facial-Expression-Recognition.Pytorch](https://github.com/WuJie1010/Facial-Expression-Recognition.Pytorch/issues/1)

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
あーなるほど
そのブランチpushしてもらっていいですか

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
すみません消しちゃったので新しく作ってもらって大丈夫です🙇‍♂️

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
残しましょう 😸

**Comment by yamamoto-yuta** [comment]
https://github.com/richcat-dev/richcat/issues/55#issuecomment-743083969

**Comment by yamamoto-yuta** [comment]
https://github.com/richcat-dev/richcat/issues/55#issuecomment-743691414
