### ISSUE TITLE
ディレクトリを指定したときにPythonのエラーが出てくる

### ISSUE THREAD

**Issue by ShotaroKataoka** [richcat-dev/richcat#39]
![image](https://user-images.githubusercontent.com/42331656/101436280-376da980-3951-11eb-99bc-88682a4c1e43.png)
ディレクトリを判定してエラーを表示するようにするか、それともディレクトリの内容（ls）もrichに表示するようにするかしてほしい

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
エラー表示が普通でしょうけど，ls結果をrich表示するの面白そうですね

**Comment by ShotaroKataoka** [comment]
そうっすね
例えばRichに[カラム機能](https://github.com/willmcgugan/rich#columns)があるけどネタとしてはこれ使っても面白いかもね

**Comment by ShotaroKataoka** [comment]
`-t`でcsvとかmarkdownとか選べても面白いかもね

# csv
| name | type | owner | permission | ... |
| ------ | ----- | ------- | ------------ | -- |
| richcat | dir | kataoka | rwxrwxrwx | ... |
| richcat.py | file | kataoka | rwxrwxrwx | ... |

とかみたいな感じで

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
カラム機能はlsで良くね？となったので一旦保留にします．ひとまず従来のcatの機能をそのまま実装します．

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
そうですね！まずはエラー文をprintするだけにしましょう！
https://github.com/richcat-dev/richcat/issues/48#issue-759936406
次のステップに行く前にここに書いてるようなRichMaker関連での議論をしておきたいです．
