### ISSUE TITLE
表示幅自動調整機能

### ISSUE THREAD

**Issue by ShotaroKataoka** [richcat-dev/richcat#42]
文字数でwidthを自動調整するようにすれば綺麗に表示できるのでは？

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
これよりも
![image](https://user-images.githubusercontent.com/42331656/101593005-96efb600-3a32-11eb-84b9-ab803a3d3c6b.png)
こっちの方が見た目いい
![image](https://user-images.githubusercontent.com/42331656/101593072-b38bee00-3a32-11eb-976f-e410caa360d9.png)
あと #53 でいってるように灰色の方がいい


他ファイルの場合もこんなに余白要らない
![image](https://user-images.githubusercontent.com/42331656/101592903-60b23680-3a32-11eb-9a19-b5343ed5d9a1.png)
こっちの方が綺麗っぽい
![image](https://user-images.githubusercontent.com/42331656/101592951-77f12400-3a32-11eb-99af-cdcb534b1de4.png)

**Comment by ShotaroKataoka** [comment]
stty sizeを最大幅にしつつ，表示テキストの最大長で自動的に変えるようにするのがよさそう

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
ファイル読み取りをwidth決定後にRichMakerでやってるからめんどいなこれ
RichMakerのファイル読み取り処理を最初の方でやった方がいいかもね

**Comment by yamamoto-yuta** [comment]
#53 も一緒にやっちゃいます
