### ISSUE TITLE
AbstractRichMakerのinitでfilepathだけじゃなくてfilecontentを入れれるようにする

### ISSUE THREAD

**Issue by ShotaroKataoka** [richcat-dev/richcat#48]
## 提案
今の実装はinitでfilepathを入れて，print時にreadしている

filepathかfilecontentのどっちかを入力するようにしといて
filepathがあるときはinit時にreadするようにしてfilecontentに入れる
filecontentがあるときはそのままfilecontentで持っておく

こうすれば，readとprintが分割されるので，もう少し柔軟な実装ができそう
将来的にecho的な実装をしたくなっても実現しやすいと思う

**Comment by ShotaroKataoka** [comment]
RichMakerで気になった点
- print関数に機能が載りすぎている
  - make_rich_text, read_file, printは分割した方がよさそう
- read_fileに引数がない（なくても問題ないけどfile_pathを引数として取る方が分かりやすい）

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
自分も同じこと考えてたので，v0.3でリファクタリングしてしまいましょう！

**Comment by yamamoto-yuta** [comment]
- _init__内で↓を行う
  - ファイル読み込み
  - richtextの生成
  - widthの決定
    - 通常メソッドで，必要に応じでoverrideする

**Comment by yamamoto-yuta** [comment]
#56

**Comment by yamamoto-yuta** [comment]
@#56

**Comment by yamamoto-yuta** [comment]
github/richcat #56
