### ISSUE TITLE
ipynb対応

### ISSUE THREAD

**Issue by ShotaroKataoka** [richcat-dev/richcat#5]

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
これ良さげです
https://faculty.ai/blog/viewing-jupyter-notebooks-on-the-command-line/

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
いいね！
ただ１コマンドじゃないとpreviewに乗せるのめんどいし，依存も増えるから参考にしながらipynbに対応しよう
これはipynb以外対応してないっぽいし，コマンド１つに集約させた方がいいと思う

**Comment by ShotaroKataoka** [comment]
色付けは`pygments`でやってるっぽい
入力は
```python
from jupyter_core.application import NoStart
from nbconvert.nbconvertapp import NbConvertApp
```
こいつらかな（速度が気になるが）

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
2個目のnbcat（GitHubリポジトリ）は1コマンドでできそうな雰囲気ありそうですけど，どうですかね？

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
fzte的には他の拡張子に対応してないから分岐しないといけないのがちょっとめんどくさいんだよね
richcat単体での動作を考えても，とりあえず対応できるやつは（たとえ既存のやつがあったとしても）対応した方がいいと思う
richcatでなんでも開けるってのが価値だと思うので

**Comment by ShotaroKataoka** [comment]
あと簡単なモックアップ作ってみた
![image](https://user-images.githubusercontent.com/42331656/99542702-b710f400-29f5-11eb-8a15-8743318f7aa6.png)

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
こっちの方が断然いいですね！

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
ケンカして勝ちましょう！

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
コード部はSyntaxをPanelで囲むといい（Panelは線で囲ってくれる）
出力はMarkdownのコードブロックかな
Tracebackはコード部と同じ扱いの方が見やすいかも

Panelは１つの要素しか囲めないけどRenderGroupを使うと１つとしてみなせるようになる
詳細はhttps://rich.readthedocs.io/en/latest/ここにあった

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
こいつを早く試したいぜ．．．

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
次何するか考えてたので、これ実装してみます！

**Comment by yamamoto-yuta** [comment]
DataFrameとか使われるとしんどいので，自力で頑張るよりnbconvertとか利用したほうが良さげな気がしてきました

**Comment by yamamoto-yuta** [comment]
NBViewerってのがあるんですね
https://nbviewer.jupyter.org/

**Comment by yamamoto-yuta** [comment]
これ便利ですね
https://pypi.org/project/nbcommands/
