### ISSUE TITLE
Markdown 背景色をシンタックスみたいに灰色にした方が見やすいかも

### ISSUE THREAD

**Issue by ShotaroKataoka** [richcat-dev/richcat#53]
![image](https://user-images.githubusercontent.com/42331656/101593147-d4ecda00-3a32-11eb-921a-40108c402f6f.png)
真っ黒で区切りが分からない

![image](https://user-images.githubusercontent.com/42331656/101593179-e33af600-3a32-11eb-911d-e58f1ab6b59f.png)
こんな感じの方がいい

**Comment by ShotaroKataoka** [comment]
![image](https://user-images.githubusercontent.com/42331656/101597675-614ecb00-3a3a-11eb-8600-f7e9c26bab72.png)
コードブロックの中が灰色だから黒くしてんのか

**Comment by ShotaroKataoka** [comment]
マークダウンはいろんなデータ入るからちょい特殊かな

表とかコードブロックとか検出してそれぞれTableとかSyntaxとかで処理させた方がいいかも？

**Comment by yamamoto-yuta** [comment]
Markdown自体をPanelで囲うのが手っ取り早そうですね

**Comment by yamamoto-yuta** [comment]
Panelつけて適当にpadding入れたら予想以上にいい感じになりました！
![image](https://user-images.githubusercontent.com/55144709/101714321-ae837900-3adc-11eb-82fe-a26581685787.png)

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
おお！文書っぽい！
かなりRichだね！
