### ISSUE TITLE
パイプに失敗したとき，Pythonのエラーが出る

### ISSUE THREAD

**Issue by ShotaroKataoka** [richcat-dev/richcat#55]
![image](https://user-images.githubusercontent.com/42331656/101633812-29ac4700-3a6b-11eb-8ec1-809099c3d0e6.png)

ちなcatの場合は
![image](https://user-images.githubusercontent.com/42331656/101633771-17caa400-3a6b-11eb-8208-d9bc4863f1cc.png)

何も表示しないようにすればcatと同じ挙動になりそう

**Comment by yamamoto-yuta** [comment]
これ使えばエラーキャッチできるっぽいので，対処は簡単そうですね．
https://www.366service.com/jp/qa/aefd85584dc028908387ece0df17a128

エラーメッセージとして↓とか出そうと思います．
```
[richat error]: Broken pipe
```

**Comment by ShotaroKataoka** [comment]
print(sys.stdin.readline())

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
`sys.stdin.readline()`は入力待ちになるらしい
filepathのargparseを無しでも行けるようにして，ないときに`sys.stdin.readline()`でfilepathを入力させるようにする
それならパイプもいける

入力待ちのプロンプトがないとふつうに`richcat`をしたときに混乱するので`print("filepath > ")`とかつけたいが，つけるとパイプの時にも表示されてしまう
`--silent`とかでプロンプトを非表示にできるようにするなどする

パイプのときは`width`が取得できないらしく，`-w`を指定しないとエラーが起きる
これはまあしゃあないかな
ただしwidthがないときのエラーが長いので短くしたい

**Comment by yamamoto-yuta** [comment]
内容がこのissueより #38 の方が適切だったため，copy link しました

**Comment by yamamoto-yuta** [comment]
動作状況：

![image](https://user-images.githubusercontent.com/55144709/101985964-5ca24500-3cce-11eb-9e09-73b216f8295c.png)

![image](https://user-images.githubusercontent.com/55144709/101985949-4a280b80-3cce-11eb-815f-0a60543f0ec0.png)

**Comment by ShotaroKataoka** [comment]
修正したつもりがちょっと変なの出る
対応方法が分からないのとあんまり影響はないのでwontfixにしときます．
気が向いたらやります
