### ISSUE TITLE
[width] Syntaxでwidthを指定すると折り返さずに見切れる

### ISSUE THREAD

**Issue by yamamoto-yuta** [richcat-dev/richcat#60]
![image](https://user-images.githubusercontent.com/55144709/101724117-20fe5400-3af1-11eb-9339-0bac35d6f5d6.png)

**Comment by ShotaroKataoka** [comment]
見切れるのは仕様だと思うよ
プログラムで勝手に折り返されると意味が変わっちゃうから

**Comment by ShotaroKataoka** [comment]
`batcat`だと折り返すな
![image](https://user-images.githubusercontent.com/42331656/101727205-6aea3880-3af7-11eb-80c7-142f3bffe2c7.png)
![image](https://user-images.githubusercontent.com/42331656/101727240-7b9aae80-3af7-11eb-8a3d-38a856423bbf.png)

**Comment by ShotaroKataoka** [comment]
https://rich.readthedocs.io/en/latest/console.html#overflow
こいつでどうだ
foldを指定するとか

**Comment by ShotaroKataoka** [comment]
styleでfold,crop,ellipsisを指定できてもいいかもね

**Comment by yamamoto-yuta** [comment]
`Syntax(word_wrap=True)` で実現できました！
https://rich.readthedocs.io/en/latest/reference/syntax.html#rich.syntax.Syntax

![Uploading image.png…]()
