### ISSUE TITLE
-hオプションをかっこよくする

### ISSUE THREAD

**Issue by ShotaroKataoka** [richcat-dev/richcat#62]
`batcat -h`がかっこいいので
![image](https://user-images.githubusercontent.com/42331656/101726835-9fa9c000-3af6-11eb-8a94-543a3655dfef.png)

**Comment by ShotaroKataoka** [comment]
markdownとかにしてもいいかもね

**Comment by ShotaroKataoka** [comment]
日本語と英語を用意すると日本人に親切そう（小並）
```
-h, --help-english
     --help-japanese
```
みたいに

**Comment by ShotaroKataoka** [comment]
マークダウンにするとしたらの例

# richcat v0.4.0
A rich cat command supporting various types of files.

## OPTIONS:
| omission | option-name | description |
| -- | -- | -- |
| -t | --file-type | fjsdlfjsdfl | 
| -h | --help | Show help in English |
|   | --help-japanese | Show help in Japanese |
| -v | --version | Show version |

## ARGS:
flsdjfkldsjfldsjflsdkj~~~~~~~~

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
これのモックアップだけやります

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
![image](https://user-images.githubusercontent.com/42331656/101877757-def90f00-3bd1-11eb-9ec5-88ef6c07380b.png)
こんな感じのできました

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
素晴らしいです！それで行きましょう！
