### ISSUE TITLE
argumentが変なとき，Pythonのエラーが出る

### ISSUE THREAD

**Issue by ShotaroKataoka** [richcat-dev/richcat#63]
![image](https://user-images.githubusercontent.com/42331656/101727598-1c896980-3af8-11eb-97f2-03551dd456c6.png)

**Comment by yamamoto-yuta** [comment]
`-h`　…　ヘルプなので対応不要
`-V`　…　バージョンなので対応不要
`-t`　…　Syntax.from_pathやrichcat.mainの`if args.filetype==DIC_DEFAULT_VALUES['filetype']:`で対応済
`-w`　…　[コレ](https://qiita.com/LyricalMaestro0/items/80e6ec2d58c828977172)の`type=float`で対応
`-c`　…　argparseの`choices`で対応済
