### ISSUE TITLE
widthのエラーが長い件（その他のエラー表示についても）

### ISSUE THREAD

**Issue by ShotaroKataoka** [richcat-dev/richcat#74]
## 方法1
raiseでExceptionを返すと，そのExceptionをcatchできるというメリットがある
例えば，例外内容ごとに固有の例外を全部作っといて例外発生時にそれをraiseする

で，main()の方で
```python
try:
    func()
except MyException1 as e:
    console.print("error message1")
except MyException2 as e:
    console.print("error message2")
```
としとく．
これならエラーメッセージを一か所にまとめられる&エラー種別ごとにExceptionをraiseするだけなので，エラーメッセージを使いまわせる
エラーメッセージ部分だけうまく関数化してもいいかも

## 方法2
今のままで，raiseじゃなくてexit()を使う．
するとそのままプログラムが終了するのでエラーが表示されない

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
方法1の例
```python
class MyException1(Exception):
    __doc__ = "MyException1"

class MyException2(Exception):
    __doc__ = "MyException2"

def check_error(error):
    if error.__doc__ == "MyException1":
        print("error: raise error1")
    elif error.__doc__ == "MyException2":
        print("error: raise error2")
    else:
        print("error: some error")

def main():
    raise MyException1

try:
    main()
except Exception as e:
    check_error(e)
```

このとき
![image](https://user-images.githubusercontent.com/42331656/101971784-27b6d380-3c77-11eb-9141-a1d5d1a88f1f.png)


これが正しいかは分からない（とくに__doc__を使ってる部分）

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
方法1で行きましょう！
