### ISSUE TITLE
pipe入力時に`-t csv`を指定するとwidthエラーが出る

### ISSUE THREAD

**Issue by yamamoto-yuta** [richcat-dev/richcat#83]
![image](https://user-images.githubusercontent.com/55144709/101985810-945cbd00-3ccd-11eb-8832-86a39a3a299f.png)

**Comment by yamamoto-yuta** [comment]
↓を試す
- `tput cols`
- `stty -F /dev/tty`

**Comment by ShotaroKataoka** [comment]
![image](https://user-images.githubusercontent.com/42331656/151648171-3c4902d2-217b-4519-96e3-ec91ea6bbf4a.png)

`stty size -F /dev/tty`で解決しそう

**Comment by yamamoto-yuta** [comment]
`tput cols` でも行けそうですね。
```
❯ echo | tput cols
188
```

**Comment by yamamoto-yuta** [comment]
https://github.com/richcat-dev/richcat/issues/83#issuecomment-1024833241 の2つを試してみたところ、pipe入力は治りました。ただ、#29 の問題は依然として残ったままです。

```python
terminal_width = os.popen('tput cols', 'r').read()
```

![image](https://user-images.githubusercontent.com/55144709/151687203-aa34af9c-6a8d-4b90-9a66-7f432a4b2188.png)

```python
terminal_width = os.popen('stty size -F /dev/tty').read().split()[1]
```

![image](https://user-images.githubusercontent.com/55144709/151687293-0f1926a1-5a4b-41f8-9612-90defe884eb3.png)
